### PR TITLE
Fix warning with vala 0.34 and bring minor improvements

### PR DESCRIPTION
**Pull request by arteymix**
There's only a couple of Valadoc errors left due to incorrect markup.

### CODE REVIEW

**Comment by rainwoodman** [comment]
Thanks! I'll merge this. We need to add a travis bot to this project.

**Comment by arteymix** [comment]
I can set that for you, I have a layout somewhere..

**Comment by rainwoodman** [comment]
That' would be great!

**Comment by arteymix** [comment]
I suggest that you enable it now so that it can be triggered on the coming PR I'm preparing :)

**Comment by rainwoodman** [comment]
I may have lost my fengy-research account / password. Let me see what I can do.

**Comment by rainwoodman** [comment]
OK. I found the password. Transferred to my new account and travis-ci is enabled.

**Pull request merged**
